language: node_js
node_js:
- '9'
script:
- npm run travis-test && npm run prod
before_deploy:
- rm -rf node_modules/react node_modules/react-dom
deploy:
  provider: npm
  email: julien.ducro@deskpro.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: deskpro/react-components
